KeyError in line 45 of /home/kgoldmann/Documents/Git/peac/Snakefile:
0
  File "/home/kgoldmann/Documents/Git/peac/Snakefile", line 143, in <module>
  File "/home/kgoldmann/Documents/Git/peac/Snakefile", line 45, in read_samples
  File "/home/kgoldmann/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in __getitem__
  File "/home/kgoldmann/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2658, in get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
